<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Yutaka" name="Default test" tests="63" failures="9" timestamp="26 Oct 2015 20:31:25 GMT" time="0.136" errors="0">
  <testcase name="testReverseStringAO" time="0.035" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringAO" time="0.002" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringAO" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringAO" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringAO" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringAO" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringAO" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringAO" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringAO" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringCharactersAP" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringCharactersAP" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringCharactersAP" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringCharactersAP" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringCharactersAP" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringCharactersAP" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringCharactersAP" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringCharactersAP" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringCharactersAP" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringCharactersLL" time="0.003" classname="com.sqa.ao.helped.RevTests">
    <failure type="java.lang.AssertionError" message="expected [tset] but found [tttt]">
      <![CDATA[java.lang.AssertionError: expected [tset] but found [tttt]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.sqa.ao.helped.RevTests.testReverseStringCharactersLL(RevTests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testReverseStringCharactersLL -->
  <testcase name="testReverseStringCharactersLL" time="0.001" classname="com.sqa.ao.helped.RevTests">
    <failure type="java.lang.AssertionError" message="expected [sessalc avaj] but found [jjjjjjjjjjjj]">
      <![CDATA[java.lang.AssertionError: expected [sessalc avaj] but found [jjjjjjjjjjjj]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.sqa.ao.helped.RevTests.testReverseStringCharactersLL(RevTests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testReverseStringCharactersLL -->
  <testcase name="testReverseStringCharactersLL" time="0.001" classname="com.sqa.ao.helped.RevTests">
    <failure type="java.lang.AssertionError" message="expected [elgoog] but found [gggggg]">
      <![CDATA[java.lang.AssertionError: expected [elgoog] but found [gggggg]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.sqa.ao.helped.RevTests.testReverseStringCharactersLL(RevTests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testReverseStringCharactersLL -->
  <testcase name="testReverseStringCharactersLL" time="0.001" classname="com.sqa.ao.helped.RevTests">
    <failure type="java.lang.AssertionError" message="expected [gu gO] but found [OOOOO]">
      <![CDATA[java.lang.AssertionError: expected [gu gO] but found [OOOOO]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.sqa.ao.helped.RevTests.testReverseStringCharactersLL(RevTests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testReverseStringCharactersLL -->
  <testcase name="testReverseStringCharactersLL" time="0.0" classname="com.sqa.ao.helped.RevTests">
    <failure type="java.lang.AssertionError" message="expected [h aysydy] but found [yyyyyyyy]">
      <![CDATA[java.lang.AssertionError: expected [h aysydy] but found [yyyyyyyy]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.sqa.ao.helped.RevTests.testReverseStringCharactersLL(RevTests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testReverseStringCharactersLL -->
  <testcase name="testReverseStringCharactersLL" time="0.001" classname="com.sqa.ao.helped.RevTests">
    <failure type="java.lang.AssertionError" message="expected [6 5 4321] but found [11111111]">
      <![CDATA[java.lang.AssertionError: expected [6 5 4321] but found [11111111]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.sqa.ao.helped.RevTests.testReverseStringCharactersLL(RevTests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testReverseStringCharactersLL -->
  <testcase name="testReverseStringCharactersLL" time="0.001" classname="com.sqa.ao.helped.RevTests">
    <failure type="java.lang.AssertionError" message="expected [3 2 1] but found [11111]">
      <![CDATA[java.lang.AssertionError: expected [3 2 1] but found [11111]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.sqa.ao.helped.RevTests.testReverseStringCharactersLL(RevTests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testReverseStringCharactersLL -->
  <testcase name="testReverseStringCharactersLL" time="0.0" classname="com.sqa.ao.helped.RevTests">
    <failure type="java.lang.AssertionError" message="expected [a ba a] but found [aaaaaa]">
      <![CDATA[java.lang.AssertionError: expected [a ba a] but found [aaaaaa]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.sqa.ao.helped.RevTests.testReverseStringCharactersLL(RevTests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testReverseStringCharactersLL -->
  <testcase name="testReverseStringCharactersLL" time="0.001" classname="com.sqa.ao.helped.RevTests">
    <failure type="java.lang.AssertionError" message="expected [a     1] but found [1111111]">
      <![CDATA[java.lang.AssertionError: expected [a     1] but found [1111111]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.sqa.ao.helped.RevTests.testReverseStringCharactersLL(RevTests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testReverseStringCharactersLL -->
  <testcase name="testReverseStringMS" time="0.002" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringMS" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringMS" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringMS" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringMS" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringMS" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringMS" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringMS" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringMS" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringPN" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringPN" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringPN" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringPN" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringPN" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringPN" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringPN" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringPN" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringPN" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringRA" time="0.002" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringRA" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringRA" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringRA" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringRA" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringRA" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringRA" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringRA" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringRA" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringTS" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringTS" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringTS" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringTS" time="0.001" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringTS" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringTS" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringTS" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringTS" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
  <testcase name="testReverseStringTS" time="0.0" classname="com.sqa.ao.helped.RevTests"/>
</testsuite> <!-- Default test -->
